# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  input:          GFM

# Permalinks
permalink:        pretty

# Setup
title:            Artigos e Livros
description:      Materiais separados por área
url:              http://miiticoxd.github.com
baseurl:          /semester-biology
email:            assiz.christian@gmail.com
feedbackurl:      
author:
  name:           'Christian Assiz'
  url:            http://miiticoxd.github.com

github:
  repo:           https://miiticoxd.github.io/semester-biology/
  #               Be sure the 'Issues' feature is activated in 'Settings'
